{
 "title": "Monitor 服务 - 方法 - 各项指标查询",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "service",
    "label": "服务名称",
    "query": "eqxiu.mall.product.service.api.ProductServiceApi"
   }
  ]
 },
 "panels": [
  {
   "title": "$service 各个方法调用次数统计 (总数 / 分钟)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "database": "app",
     "dateTimeColDataType": "create_at",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    t,\n    groupArray((method, c)) AS groupArr\nFROM\n(\n    SELECT\n        (intDiv(toUInt32(create_at), 60) * 60) * 1000 AS t,\n        method,\n        sum(success) c\n    FROM app.db_logs\n    WHERE create_at >= toDateTime($from) and service='$service'\n    GROUP BY\n        t,\n        method\n    ORDER BY\n        t,\n        method\n)\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT     t,     groupArray((method, c)) AS groupArr FROM (     SELECT         (intDiv(toUInt32(create_at), 60) * 60) * 1000 AS t,         method,         sum(success) c     FROM app.db_logs     WHERE create_at >= toDateTime(1568272861) and service='eqxiu.mall.product.service.api.ProductServiceApi'     GROUP BY         t,         method     ORDER BY         t,         method ) GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "db_logs"
    }
   ]
  },
  {
   "title": "$service 各个方法失败调用次数统计 ( 总数 / 分钟)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "database": "app",
     "dateTimeColDataType": "create_at",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    t,\n    groupArray((method, c)) AS groupArr\nFROM\n(\n    SELECT\n        (intDiv(toUInt32(create_at), 60) * 60) * 1000 AS t,\n        method,\n        sum(failure) c\n    FROM app.db_logs\n    WHERE create_at >= toDateTime($from) and service='$service'\n    GROUP BY\n        t,\n        method\n    ORDER BY\n        t,\n        method\n)\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT     t,     groupArray((method, c)) AS groupArr FROM (     SELECT         (intDiv(toUInt32(create_at), 60) * 60) * 1000 AS t,         method,         sum(failure) c     FROM app.db_logs     WHERE create_at >= toDateTime(1568272833) and service='eqxiu.mall.product.service.api.ProductServiceApi'     GROUP BY         t,         method     ORDER BY         t,         method ) GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "db_logs"
    }
   ]
  },
  {
   "title": "$service 各个方法最大响应时间 ( 毫秒 ms)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "database": "app",
     "dateTimeColDataType": "create_at",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    t,\n    groupArray((method, c)) AS groupArr\nFROM\n(\n    SELECT\n        (intDiv(toUInt32(create_at), 60) * 60) * 1000 AS t,\n        method,\n        max(maxElapsed) as  c\n    FROM app.db_logs\n    WHERE create_at >= toDateTime($from) and service='$service'\n    GROUP BY\n        t,\n        method\n    ORDER BY\n        t,\n        method\n)\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT     t,     groupArray((method, c)) AS groupArr FROM (     SELECT         (intDiv(toUInt32(create_at), 60) * 60) * 1000 AS t,         method,         max(maxElapsed) as  c     FROM app.db_logs     WHERE create_at >= toDateTime(1568272891) and service='eqxiu.mall.product.service.api.ProductServiceApi'     GROUP BY         t,         method     ORDER BY         t,         method ) GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "db_logs"
    }
   ]
  },
  {
   "title": "$service 各个方法平均响应时间 ( 毫秒 ms)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "database": "app",
     "dateTimeColDataType": "create_at",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    t,\n    groupArray((method, c)) AS groupArr\nFROM\n(\n    SELECT\n        (intDiv(toUInt32(create_at), 60) * 60) * 1000 AS t,\n        method,\n        sum(elapsed) / sum(success) as  c\n    FROM app.db_logs\n    WHERE create_at >= toDateTime($from) and service='$service'\n    GROUP BY\n        t,\n        method\n    ORDER BY\n        t,\n        method\n)\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT     t,     groupArray((method, c)) AS groupArr FROM (     SELECT         (intDiv(toUInt32(create_at), 60) * 60) * 1000 AS t,         method,         sum(elapsed) / sum(success) as  c     FROM app.db_logs     WHERE create_at >= toDateTime(1568272833) and service='eqxiu.mall.product.service.api.ProductServiceApi'     GROUP BY         t,         method     ORDER BY         t,         method ) GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "db_logs"
    }
   ]
  }
 ]
}