{
 "title": "Monitor 首页",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "全网 成功请求数  / 每秒 (QPS) ",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "database": "app",
     "dateTimeColDataType": "create_at",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT     (intDiv(toUInt32(create_at), 60) * 60) * 1000 as t, \n\nsum(success) / 60 as success \nFROM app.db_logs WHERE create_at >= toDateTime($from)\nGROUP BY t \nORDER BY t\n",
     "rawQuery": "SELECT     (intDiv(toUInt32(create_at), 60) * 60) * 1000 as t,   sum(success) / 60 as success  FROM app.db_logs WHERE create_at >= toDateTime(1568253267) GROUP BY t  ORDER BY t",
     "round": "0s",
     "table": "db_logs"
    }
   ]
  },
  {
   "title": "请求失败总数 TOP 25",
   "type": "table-old",
   "gridPos": { "h": 17, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "database": "app",
     "dateTimeColDataType": "create_at",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    service,\n    method,\n    sum(failure) as c\nFROM $table\nWHERE create_at >= toDateTime($from) and (provider is not null and provider != '')\ngroup by service ,method\norder by c desc limit 25\n",
     "rawQuery": "SELECT     service,     method,     sum(failure) as c FROM app.db_logs WHERE create_at >= toDateTime(1568253267) and (provider is not null and provider != '') group by service ,method order by c desc limit 25",
     "round": "0s",
     "table": "db_logs"
    }
   ]
  },
  {
   "title": "全网 失败请求总数 (每分钟)",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    t,\n    groupArray((service, c)) AS groupArr\nFROM\n(\n    SELECT\n        (intDiv(toUInt32(create_at), 60) * 60) * 1000 AS t,\n        service,\n        sum(failure/60) c\n    FROM app.db_logs\n    WHERE create_at >= toDateTime($from) \n    GROUP BY\n        t,\n        service\n    ORDER BY\n        t,\n        service\n)\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT     t,     groupArray((service, c)) AS groupArr FROM (     SELECT         (intDiv(toUInt32(create_at), 60) * 60) * 1000 AS t,         service,         sum(failure/60) c     FROM app.db_logs     WHERE create_at >= toDateTime(1568253267)      GROUP BY         t,         service     ORDER BY         t,         service ) GROUP BY t ORDER BY t",
     "round": "0s"
    }
   ]
  }
 ]
}