apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    description: waf-to-es-show
  labels:
    qcloud-app: waf-to-es-show
  name: waf-to-es-show
  namespace: eqxiu-ops
spec:
  replicas: 2
  selector:
    matchLabels:
      qcloud-app: waf-to-es-show
  template:
    metadata:
      labels:
        qcloud-app: waf-to-es-show
    spec:
      containers:
      - name: waf-to-es
        image: ccr.ccs.tencentyun.com/eqxiu/waf-to-es
        args:
          - -group_id=kafka-to-mysql
          - -topic=gateway_original_show
        imagePullPolicy: Always
        resources:
          limits:
            memory: 1024Mi
          requests:
            memory: 800Mi
        securityContext:
          privileged: false
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: qcloudregistrykey
      - name: tencenthubkey
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
  revisionHistoryLimit: 5
  progressDeadlineSeconds: 600
  minReadySeconds: 10
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate