// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.12.1
// source: clazz_method_param.proto

package dubbo

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type ProxyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Application   string   `protobuf:"bytes,1,opt,name=application,proto3" json:"application,omitempty"`
	InterfaceName string   `protobuf:"bytes,2,opt,name=interfaceName,proto3" json:"interfaceName,omitempty"`
	Version       string   `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Group         string   `protobuf:"bytes,4,opt,name=group,proto3" json:"group,omitempty"`
	Method        string   `protobuf:"bytes,5,opt,name=method,proto3" json:"method,omitempty"`
	Types         []string `protobuf:"bytes,6,rep,name=types,proto3" json:"types,omitempty"`
	Values        string   `protobuf:"bytes,7,opt,name=values,proto3" json:"values,omitempty"`
}

func (x *ProxyRequest) Reset() {
	*x = ProxyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_clazz_method_param_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProxyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProxyRequest) ProtoMessage() {}

func (x *ProxyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clazz_method_param_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProxyRequest.ProtoReflect.Descriptor instead.
func (*ProxyRequest) Descriptor() ([]byte, []int) {
	return file_clazz_method_param_proto_rawDescGZIP(), []int{0}
}

func (x *ProxyRequest) GetApplication() string {
	if x != nil {
		return x.Application
	}
	return ""
}

func (x *ProxyRequest) GetInterfaceName() string {
	if x != nil {
		return x.InterfaceName
	}
	return ""
}

func (x *ProxyRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ProxyRequest) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *ProxyRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *ProxyRequest) GetTypes() []string {
	if x != nil {
		return x.Types
	}
	return nil
}

func (x *ProxyRequest) GetValues() string {
	if x != nil {
		return x.Values
	}
	return ""
}

type ProxyReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result string `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *ProxyReply) Reset() {
	*x = ProxyReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_clazz_method_param_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProxyReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProxyReply) ProtoMessage() {}

func (x *ProxyReply) ProtoReflect() protoreflect.Message {
	mi := &file_clazz_method_param_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProxyReply.ProtoReflect.Descriptor instead.
func (*ProxyReply) Descriptor() ([]byte, []int) {
	return file_clazz_method_param_proto_rawDescGZIP(), []int{1}
}

func (x *ProxyReply) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

var File_clazz_method_param_proto protoreflect.FileDescriptor

var file_clazz_method_param_proto_rawDesc = []byte{
	0x0a, 0x18, 0x63, 0x6c, 0x61, 0x7a, 0x7a, 0x5f, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x5f, 0x70,
	0x61, 0x72, 0x61, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x64, 0x75, 0x62, 0x62,
	0x6f, 0x22, 0xcc, 0x01, 0x0a, 0x0c, 0x50, 0x72, 0x6f, 0x78, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x61, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x61, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x24, 0x0a, 0x0d, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63,
	0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x69, 0x6e, 0x74,
	0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65,
	0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x65,
	0x74, 0x68, 0x6f, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6d, 0x65, 0x74, 0x68,
	0x6f, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x79, 0x70, 0x65, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x05, 0x74, 0x79, 0x70, 0x65, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73,
	0x22, 0x24, 0x0a, 0x0a, 0x50, 0x72, 0x6f, 0x78, 0x79, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x16,
	0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x32, 0x47, 0x0a, 0x0c, 0x50, 0x72, 0x6f, 0x78, 0x79, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x37, 0x0a, 0x0b, 0x49, 0x6e, 0x76, 0x6f, 0x6b, 0x65,
	0x50, 0x72, 0x6f, 0x78, 0x79, 0x12, 0x13, 0x2e, 0x64, 0x75, 0x62, 0x62, 0x6f, 0x2e, 0x50, 0x72,
	0x6f, 0x78, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x11, 0x2e, 0x64, 0x75, 0x62,
	0x62, 0x6f, 0x2e, 0x50, 0x72, 0x6f, 0x78, 0x79, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x42,
	0x22, 0x0a, 0x1c, 0x6f, 0x72, 0x67, 0x2e, 0x61, 0x70, 0x61, 0x63, 0x68, 0x65, 0x2e, 0x64, 0x75,
	0x62, 0x62, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x48,
	0x01, 0x50, 0x01, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_clazz_method_param_proto_rawDescOnce sync.Once
	file_clazz_method_param_proto_rawDescData = file_clazz_method_param_proto_rawDesc
)

func file_clazz_method_param_proto_rawDescGZIP() []byte {
	file_clazz_method_param_proto_rawDescOnce.Do(func() {
		file_clazz_method_param_proto_rawDescData = protoimpl.X.CompressGZIP(file_clazz_method_param_proto_rawDescData)
	})
	return file_clazz_method_param_proto_rawDescData
}

var file_clazz_method_param_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_clazz_method_param_proto_goTypes = []interface{}{
	(*ProxyRequest)(nil), // 0: dubbo.ProxyRequest
	(*ProxyReply)(nil),   // 1: dubbo.ProxyReply
}
var file_clazz_method_param_proto_depIdxs = []int32{
	0, // 0: dubbo.ProxyService.InvokeProxy:input_type -> dubbo.ProxyRequest
	1, // 1: dubbo.ProxyService.InvokeProxy:output_type -> dubbo.ProxyReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_clazz_method_param_proto_init() }
func file_clazz_method_param_proto_init() {
	if File_clazz_method_param_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_clazz_method_param_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProxyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_clazz_method_param_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProxyReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_clazz_method_param_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_clazz_method_param_proto_goTypes,
		DependencyIndexes: file_clazz_method_param_proto_depIdxs,
		MessageInfos:      file_clazz_method_param_proto_msgTypes,
	}.Build()
	File_clazz_method_param_proto = out.File
	file_clazz_method_param_proto_rawDesc = nil
	file_clazz_method_param_proto_goTypes = nil
	file_clazz_method_param_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ProxyServiceClient is the client API for ProxyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ProxyServiceClient interface {
	InvokeProxy(ctx context.Context, in *ProxyRequest, opts ...grpc.CallOption) (*ProxyReply, error)
}

type proxyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProxyServiceClient(cc grpc.ClientConnInterface) ProxyServiceClient {
	return &proxyServiceClient{cc}
}

func (c *proxyServiceClient) InvokeProxy(ctx context.Context, in *ProxyRequest, opts ...grpc.CallOption) (*ProxyReply, error) {
	out := new(ProxyReply)
	err := c.cc.Invoke(ctx, "/dubbo.ProxyService/InvokeProxy", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProxyServiceServer is the server API for ProxyService service.
type ProxyServiceServer interface {
	InvokeProxy(context.Context, *ProxyRequest) (*ProxyReply, error)
}

// UnimplementedProxyServiceServer can be embedded to have forward compatible implementations.
type UnimplementedProxyServiceServer struct {
}

func (*UnimplementedProxyServiceServer) InvokeProxy(context.Context, *ProxyRequest) (*ProxyReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InvokeProxy not implemented")
}

func RegisterProxyServiceServer(s *grpc.Server, srv ProxyServiceServer) {
	s.RegisterService(&_ProxyService_serviceDesc, srv)
}

func _ProxyService_InvokeProxy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProxyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProxyServiceServer).InvokeProxy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dubbo.ProxyService/InvokeProxy",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProxyServiceServer).InvokeProxy(ctx, req.(*ProxyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ProxyService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "dubbo.ProxyService",
	HandlerType: (*ProxyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InvokeProxy",
			Handler:    _ProxyService_InvokeProxy_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "clazz_method_param.proto",
}
